apiVersion: v1
kind: Service
metadata:
  name: bert-deepspeed-svc
spec:
  selector:
    app: bert-deepspeed
  clusterIP: None
  ports:
  - name: ssh
    port: 22
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: bert-deepspeed
  name: bert-deepspeed
spec:
  podManagementPolicy: "Parallel"
  serviceName: bert-deepspeed-svc
  replicas: 3
  selector:
    matchLabels:
      app: bert-deepspeed
  template:
    metadata:
      labels:
        app: bert-deepspeed
    spec:
      containers:
      - image: us-docker.pkg.dev/PROJECT_ID/AR_REPO/bert:deepspeed
        name: bert-deepspeed
        imagePullPolicy: Always
        volumeMounts:
        - name: hostfile
          mountPath: "/config"
          readOnly: true
        - mountPath: /dev/shm
          name: dshm
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: hostfile
        configMap:
          name: hostfile-config
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 1G
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hostfile-config
data:
  hostfile: |
    bert-deepspeed-0.bert-deepspeed-svc slots=1
    bert-deepspeed-1.bert-deepspeed-svc slots=1
    bert-deepspeed-2.bert-deepspeed-svc slots=1
