apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: controller
  name: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/artifact-vllm/vllm-server:fastchat
        name: controller
        command:
          - python3
          - -m
          - fastchat.serve.controller
          - --host
          - "0.0.0.0"
          - --port
          - "21001"
        ports:
        - containerPort: 21001
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool

---

apiVersion: v1
kind: Service
metadata:
  name: controller-svc
spec:
  ports:
  - port: 21001
    protocol: TCP
    targetPort: 21001
  selector:
    app: controller
  type: ClusterIP