apiVersion: v1
kind: Service
metadata:
  name: llama2-deepspeed-svc
spec:
  selector:
    app: llama2-deepspeed
  clusterIP: None
  ports:
  - name: ssh
    port: 22
    targetPort: 2222
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: llama2-deepspeed
  name: llama2-deepspeed
spec:
  podManagementPolicy: "Parallel"
  serviceName: llama2-deepspeed-svc
  replicas: 4
  selector:
    matchLabels:
      app: llama2-deepspeed
  template:
    metadata:
      labels:
        app: llama2-deepspeed
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/cpu-limit: 500m
        gke-gcsfuse/memory-limit: 100Mi
        gke-gcsfuse/ephemeral-storage-limit: 30Gi
    spec:
      containers:
      - image: us-docker.pkg.dev/PROJECT_ID/AR_REPO/llama2:deepspeed
        name: llama2-deepspeed
        imagePullPolicy: Always
        volumeMounts:
        - name: hostfile
          mountPath: "/config"
          readOnly: true
        - name: log
          mountPath: /log
          readOnly: false
        - mountPath: /dev/shm
          name: dshm
        - name: gcs-fuse-csi-ephemeral
          mountPath: /gcs
          readOnly: true
        resources:
          limits:
            nvidia.com/gpu: 2
      volumes:
      - name: hostfile
        configMap:
          name: hostfile-config
      - name: log
        hostPath:
          path: /tmp
          type: Directory
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 48G
      - name: gcs-fuse-csi-ephemeral
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: BUCKET_NAME
            mountOptions: "implicit-dirs"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hostfile-config
data:
  hostfile: |
    llama2-deepspeed-0.llama2-deepspeed-svc slots=2
    llama2-deepspeed-1.llama2-deepspeed-svc slots=2
    llama2-deepspeed-2.llama2-deepspeed-svc slots=2
    llama2-deepspeed-3.llama2-deepspeed-svc slots=2
