apiVersion: v1
kind: Service
metadata:
  name: t5-deepspeed-svc
spec:
  selector:
    app: t5-deepspeed
  clusterIP: None
  ports:
  - name: ssh
    port: 22
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: t5-deepspeed
  name: t5-deepspeed
spec:
  podManagementPolicy: "Parallel"
  serviceName: t5-deepspeed-svc
  replicas: 4
  selector:
    matchLabels:
      app: t5-deepspeed
  template:
    metadata:
      labels:
        app: t5-deepspeed
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: fuse-sa
      containers:
      - image: us-docker.pkg.dev/PROJECT_ID/AR_REPO/t5:deepspeed
        name: t5-deepspeed
        #command: ["/bin/sh", "-c", "/start.sh"]
        imagePullPolicy: Always
        volumeMounts:
        - name: hostfile
          mountPath: "/config"
          readOnly: true
        - name: log
          mountPath: /log
          readOnly: false
        - mountPath: /dev/shm
          name: dshm
        - name: gcs-fuse-csi-ephemeral
          mountPath: /gcs
          readOnly: false
        resources:
          limits:
            nvidia.com/gpu: 2
      volumes:
      - name: hostfile
        configMap:
          name: hostfile-config
      - name: log
        hostPath:
          path: /tmp
          type: Directory
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 30G
      - name: gcs-fuse-csi-ephemeral
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: BUCKET_NAME
            mountOptions: "implicit-dirs"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hostfile-config
data:
  hostfile: |
    t5-deepspeed-0.t5-deepspeed-svc slots=2
    t5-deepspeed-1.t5-deepspeed-svc slots=2
    t5-deepspeed-2.t5-deepspeed-svc slots=2
    t5-deepspeed-3.t5-deepspeed-svc slots=2
